#!/bin/bash
#
#  termubitd The termubit core server.
#
#
# chkconfig: 345 80 20
# description: termubitd
# processname: termubitd
#

# Source function library.
. /etc/init.d/functions

# you can override defaults in /etc/sysconfig/termubitd, see below
if [ -f /etc/sysconfig/termubitd ]; then
        . /etc/sysconfig/termubitd
fi

RETVAL=0

prog=termubitd
# you can override the lockfile via TRBCOIND_LOCKFILE in /etc/sysconfig/termubitd
lockfile=${TRBCOIND_LOCKFILE-/var/lock/subsys/termubitd}

# termubitd defaults to /usr/bin/termubitd, override with TRBCOIND_BIN
termubitd=${TRBCOIND_BIN-/usr/bin/termubitd}

# termubitd opts default to -disablewallet, override with TRBCOIND_OPTS
termubitd_opts=${TRBCOIND_OPTS--disablewallet}

start() {
    echo -n $"Starting $prog: "
    daemon $DAEMONOPTS $termubitd $termubitd_opts
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch $lockfile
    return $RETVAL
}

stop() {
    echo -n $"Stopping $prog: "
    killproc $prog
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && rm -f $lockfile
    return $RETVAL
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status $prog
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: service $prog {start|stop|status|restart}"
        exit 1
        ;;
esac
